CREATE OR REPLACE PACKAGE XX_EMPLOYEES_PKG
AS

    PROCEDURE CREATE_EMPLOYEE(P_NAME VARCHAR2, P_SURNAME VARCHAR2, P_EMAIL VARCHAR2, P_TITLE VARCHAR2, P_SALARY_GROSS NUMBER);

END XX_EMPLOYEES_PKG;