DROP TABLE XX_EMPLOYEES;
DROP TABLE XX_DEPARTMENTS;
DROP TABLE XX_TITLES;


CREATE TABLE XX_EMPLOYEES(EMP_ID NUMBER PRIMARY KEY, NAME VARCHAR2(75), SURNAME VARCHAR2(75), EMAIL VARCHAR2(2000), TITLE NUMBER, SALARY_GROSS NUMBER, SALARY_NETTO NUMBER);

CREATE TABLE XX_DEPARTMENTS (DEPT_ID NUMBER PRIMARY KEY, NAME VARCHAR2(75), DESCRIPTION VARCHAR2(200));

CREATE TABLE XX_TITLES (TITLE_ID NUMBER PRIMARY KEY, NAME VARCHAR2(75), DEPARTMENT NUMBER, DESCRIPTION VARCHAR2(200));

INSERT INTO XX_TITLES 
VALUES (1, 'Developer', 1, 'Develop IT solutions' );

INSERT INTO XX_TITLES 
VALUES (2, 'Architect', 1, 'Design IT solutions' );

INSERT INTO XX_TITLES 
VALUES (3, 'Manager', 1, 'Manage IT projects' );

INSERT INTO XX_DEPARTMENTS
VALUES (1, 'IT', 'Information technologies department');

select *
from XX_TITLES;

select *
from XX_DEPARTMENTS;

CREATE SEQUENCE xx_emp_id_seq
MINVALUE 1
MAXVALUE 999999999999
CYCLE;

select xx_emp_id_seq.nextval
from dual;

select *
from XX_EMPLOYEES;

DELETE FROM XX_EMPLOYEES;